#!/bin/bash

#https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
#printf "I ${RED}love${NC} Stack Overflow\n"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
OK="${GREEN}ok${NC}"
FAIL="${RED}fail${NC}"

PROXY="socks5:1.2.3.4:5841:user:password"

while true; do
    # get proxy from stdin
    read -e -p "Enter proxy settings:   " -i $PROXY PROXY
    # parse PROXY
    eval 'echo $PROXY | tr ":" "\n" | wc -l | grep -qw 5'
    ret=$?  
    if [ $ret -eq 0 ]; then
        printf "[$OK] PROXY $PROXY is valid \n"
    else
        printf "[$FAIL] string <$PROXY> does not look like string <socks5:1.2.3.4:5841:user:password> \n"
        PROXY="socks5:1.2.3.4:5841:user:password"
        continue
    fi
	TYPE=$(echo $PROXY | tr ":" "\n" | sed -n '1p')
    USER=$(echo $PROXY | tr ":" "\n" | sed -n '4p')
    PASSWORD=$(echo $PROXY | tr ":" "\n" | sed -n '5p')
    IP=$(echo $PROXY | tr ":" "\n" | sed -n '2p')
    PORT=$(echo $PROXY | tr ":" "\n" | sed -n '3p')
    # copy config
    eval "rm -f proxychains_$IP.conf; cp proxychains.conf proxychains_$IP.conf"
    ret=$?  
    if [ $ret -eq 0 ]; then
        printf "[$OK] proxychains_$IP.conf create \n"
    else
        printf "[$FAIL] proxychains_$IP.conf create \n"
        exit
    fi
    # update config
    `echo "$TYPE         $IP $PORT $USER $PASSWORD" >> proxychains_$IP.conf`
    if [ $ret -eq 0 ]; then
        printf "[$OK] proxychains_$IP.conf update \n"
    else
        printf "[$FAIL] proxychains_$IP.conf update \n"
        exit
    fi
    # docker run
    eval "docker run -d --restart always --name tm_$IP -v /root/tm/proxychains_$IP.conf:/etc/proxychains/proxychains.conf tmp"
    ret=$?
    if [ $ret -eq 0 ]; then
        printf "[$OK] Run docker container wia proxy $IP \n"
    else
        printf "[$FAIL] Run docker container wia proxy $IP \n"
        exit
    fi
    echo "-----"
    #  start another?
    while true; do
        read -e -p "Start another container (y/n)?   " -i "" -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            break
        fi
        if [[ $REPLY =~ ^[Nn]$ ]]
        then
            printf "[$OK] Exit \n"
            exit 0
        fi
    done
done
